
import './globals.css'
import Navbar from './components/Navbar'

export const metadata = {
  title: 'AM | Front-End Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
     lang="en" className='scroll-smooth'> 
      <body>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
